### ISSUE TITLE
tests can't be run in interactive session

### ISSUE THREAD

**Issue by anderspitman** [biocore/scikit-bio#871]
After the changes I made to the testing procedures, particularly using nose's ``run_exit`` method, running tests within an interactive python session causes the session to exit, and running from within ``IPython`` throws the following exception:

```
Ran 177 tests in 0.070s

OK
An exception has occurred, use %tb to see the full traceback.

SystemExit: False

To exit: use 'exit', 'quit', or Ctrl-D.
```

Looks like I'll need to detect whether we're running interactively.

**Comment by anderspitman** [comment]
Hm this might be a little tricky, since ``python -c "import skbio; skbio.test()"`` is technically an interactive session, as far as I can tell. Unless someone else knows a way to differentiate. The easiest way to solve this would be to add an ``exit`` parameter to ``TestRunner.test`` and update ours docs to instruct the users to do the following when running interactively:

``` python
>>> import skbio
>>> skbio.test(exit=False)
```

An alternative would be to not support running tests interactively and remove those instructions from our docs. I like option 1 better.

**Comment by Jorge-C** [comment]
That's too bad... If we need an argument, I feel it might be better to make it necessary for the `python -c "import ...` version rather than in a more "interative" usage (it seems more likely that users are copy/pasting the first command when following the installation instructions, whereas if they stumble upon the `skbio.test` they won't realize they need an extra argument).

**Comment by jairideout** [comment]
I think we can work around this by changing the user-level instructions to be:

```
$ python -m skbio.__init__
```

instead of 

```
python -c "import skbio; skbio.test()"
```

Then have `TestRunner` return the exit code instead of using `run_exit` and update `skbio.__init__` to pass this value to `sys.exit` within `if __name__ == '__main__':`. That way the exit code will be retained when executing the tests non-interactively, and simply returned in an interactive context.

**Comment by jairideout** [comment]
@anderspitman can I assign this to you?

**Comment by anderspitman** [comment]
@jairideout yep I got it. I like this solution.

**Comment by anderspitman** [comment]
Seems to work. @jairideout what do you think about adding a ``run_tests.py`` file in ``skbio`` rather than having this live in ``__init__.py``?

``python -m skbio.run_tests`` 

seems more clear than

``python -m skbio.__init__``

Not sure if it's worth adding another file though.

**Comment by anderspitman** [comment]
Also, invoking this way makes it so we can't pass arguments directly to ``TestRunner.test``. Currently we're only doing this to flag verbosity. Would it be preferable to add argument parsing to ``skbio.__init__`` (or ``skbio.run_tests``) or remove the verbosity option?

**Comment by jairideout** [comment]
I think removing the verbosity option for now is fine (we can always add it back later if it becomes important).

I like your idea of having a separate module for this -- what about `python -m skbio.test`?

**Comment by anderspitman** [comment]
I like ``python -m skbio.test``. I implemented it that way. One semantic caveat of that is that the ``test.py`` file shadows the ``skbio.test`` method. So if for some reason you wanted to do

``` python
from skbio import test
test()
```
That won't work anymore because it's going to import the module instead of the ``TestRunner.test`` instance. I don't think this matters.

**Comment by jairideout** [comment]
Good catch! I agree that this probably isn't a big deal.

**Comment by jairideout** [comment]
Fixed in #872.

**Comment by anderspitman** [comment]
@jairideout somewhat random coincidence, especially since we just merged this, but I was just looking at #857 and discovered that the ``test`` module/method shadowing may actually be a problem for running the tests interactively twice in a row. If you run

``` python
import skbio
skbio.test()
```

In an interactive shell it works the first time, but during the run the ``skbio.test`` module gets imported. So trying to run again in the same session predictably gives 

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```

So we may want to change the name of the ``skbio/test.py`` file after all in order to resolve #857, or just close #857 and don't worry about users trying to run the tests twice in a row in a single session, which seems like a rather limited use case.

**Comment by anderspitman** [comment]
Or even easier, remove the ``skbio.test`` method instance from ``skbio.__init__.py``. ``skbio`` level testing is handled by ``skbio.test.py`` now so it's really not necessary. We can leave the ones in the submodule init files to permit targeted testing.

**Comment by ebolyen** [comment]
:+1: for dropping it from the  __init__` it is pretty easy to just say `from skbio.test import test; test()` (which works just fine presently)

**Comment by ebolyen** [comment]
Actually some interesting news in regards to running them twice from the same environment. Our warnings aren't raised a second time, so the tests for those fail. This is just how python behaves so I think we can probably just say that we don't support testing twice from the same interactive shell. (I still don't entirely know why it would be needed anyways). If anything this "bug" (*cough* feature) prevents users from thinking the tests are failing when they aren't (since python will suppress the same warning when issued twice).

**Comment by anderspitman** [comment]
One argument for leaving `test` in `__init__.py` is that it allows the user to run all the tests in verbose mode (though realistically there will probably never be more than a couple of us who ever know or care about this fact. Hell I wrote it and I'm not even sure I care) . But this works fine the first time. So yeah I say leave it as is and close #857 until someone complains about not being able to run tests twice interactively.

**Comment by ebolyen** [comment]
Even if someone did, there isn't a good way to actually accommodate them as our tests fail the second time regardless of mechanism, as a result of the warnings being suppressed.

**Comment by anderspitman** [comment]
Right, we opened #857 to resolve that issue, possibly by doing some black magic behind the scenes to reset the warnings after running the tests.

**Comment by ebolyen** [comment]
Oh yup, there’s an entire issue about this that I have missed. Sorry about that!

**Comment by anderspitman** [comment]
No worries, like I said my vote is that it's not important enough to fix unless it becomes a viable use case.

**Comment by jairideout** [comment]
:+1:

**Comment by jairideout** [comment]
So is #857 good to close?

**Comment by ebolyen** [comment]
:+1: for close.

**Comment by jairideout** [comment]
done

**Comment by anderspitman** [comment]
:+1:
